web:
  build: docker-images/web/
  ports:
    - 5000:5000
  volumes:
    - .:/data/app
  links:
    - 'db'

db:
  build: docker-images/db/
  environment:
    POSTGRES_PASSWORD: password
  ports:
    - 5432:5432
  volumes:
    - .:/data/app

